# Generated by Django 2.2.5 on 2020-03-07 14:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200307_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 7, 14, 6, 11, 532234, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='creat_data',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 7, 14, 6, 11, 531237, tzinfo=utc)),
        ),
    ]
