# Generated by Django 2.2.5 on 2020-04-22 03:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200307_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 22, 3, 49, 32, 584295, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_data',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 22, 3, 49, 32, 583298, tzinfo=utc)),
        ),
    ]
