# Generated by Django 2.2.5 on 2020-04-22 05:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200422_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 22, 5, 1, 20, 441352, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_data',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 22, 5, 1, 20, 440354, tzinfo=utc)),
        ),
    ]
